using System;
using System.Collections.Generic;

namespace MS2000WEB.Models
{
    public partial class FOLLOW_ANTIGO
    {
        public int num { get; set; }
        public string Processo { get; set; }
        public string Parcial { get; set; }
        public string Nosso_Nr { get; set; }
        public string Cliente { get; set; }
        public string senha { get; set; }
        public string Txt_Cliente { get; set; }
        public string Txt_Nosso { get; set; }
        public string Txt_Ultimo { get; set; }
        public string Mov_Cliente { get; set; }
        public string Mov_Nosso { get; set; }
        public string Tipo { get; set; }
        public string Mercadoria { get; set; }
        public string Fornecedor { get; set; }
        public string Unidade { get; set; }
        public string Quantidade { get; set; }
        public Nullable<double> Fob_Unitario { get; set; }
        public Nullable<double> Fob_Total { get; set; }
        public string Moeda { get; set; }
        public string Forma_Paga { get; set; }
        public Nullable<System.DateTime> Rec_Proforma { get; set; }
        public string LI_NR { get; set; }
        public string Consigna { get; set; }
        public string Origem { get; set; }
        public string Porto_Embarque { get; set; }
        public string Porto_Descarga { get; set; }
        public Nullable<System.DateTime> PO_Fornecedor { get; set; }
        public string Carta_Credito { get; set; }
        public Nullable<System.DateTime> Carta_Emite { get; set; }
        public Nullable<System.DateTime> Carta_Vence { get; set; }
        public string Embarque_Previsto { get; set; }
        public Nullable<System.DateTime> Embarque_Real { get; set; }
        public string Aviao_Navio { get; set; }
        public string Transportador { get; set; }
        public string Chegada_Previsao { get; set; }
        public Nullable<System.DateTime> Chegada_Real { get; set; }
        public string BLAWB { get; set; }
        public Nullable<System.DateTime> Documentos_Cambio { get; set; }
        public Nullable<short> Dias_Cambio { get; set; }
        public Nullable<System.DateTime> Fecha_Cambio { get; set; }
        public string Despachante { get; set; }
        public Nullable<System.DateTime> Doc_Despachante { get; set; }
        public Nullable<System.DateTime> Numerario { get; set; }
        public Nullable<System.DateTime> Numerario_Para { get; set; }
        public Nullable<System.DateTime> Pag_Tributos { get; set; }
        public string DI { get; set; }
        public string DTA { get; set; }
        public string Invoice { get; set; }
        public Nullable<System.DateTime> Desembaraco_Prev { get; set; }
        public Nullable<System.DateTime> Desembaraco_Real { get; set; }
        public string Termo { get; set; }
        public Nullable<System.DateTime> Venc_Termo { get; set; }
        public Nullable<System.DateTime> Armazenagem_1 { get; set; }
        public Nullable<System.DateTime> Armazenagem_2 { get; set; }
        public string outros_doc_1 { get; set; }
        public string txt_doc_1 { get; set; }
        public string outros_doc_2 { get; set; }
        public string txt_doc_2 { get; set; }
        public string outros_doc_3 { get; set; }
        public string txt_doc_3 { get; set; }
        public string outros_doc_4 { get; set; }
        public string txt_doc_4 { get; set; }
        public string outros_doc_5 { get; set; }
        public string txt_doc_5 { get; set; }
        public string Canal { get; set; }
        public string container_1 { get; set; }
        public string container_2 { get; set; }
        public string container_3 { get; set; }
        public string container_4 { get; set; }
        public string container_5 { get; set; }
        public string container_6 { get; set; }
        public string container_7 { get; set; }
        public string container_8 { get; set; }
        public string container_9 { get; set; }
        public string container_10 { get; set; }
        public string container_11 { get; set; }
        public string container_12 { get; set; }
        public string container_13 { get; set; }
        public string container_14 { get; set; }
        public string container_15 { get; set; }
        public string container_16 { get; set; }
        public string container_17 { get; set; }
        public string container_18 { get; set; }
        public string container_19 { get; set; }
        public string container_20 { get; set; }
        public string container_21 { get; set; }
        public string container_22 { get; set; }
        public string container_23 { get; set; }
        public string container_24 { get; set; }
        public string container_25 { get; set; }
    }
}
