using System;
using System.Collections.Generic;

namespace MS2000WEB.Models
{
    public partial class Processos_Visao_Geral
    {
        public string Processo { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Importador { get; set; }
        public string CGC_CPF { get; set; }
        public Nullable<int> Atualizado { get; set; }
        public string Contratos { get; set; }
        public string Local_Inventario { get; set; }
        public Nullable<System.DateTime> Data_Chegada { get; set; }
        public string Periodo_Registro { get; set; }
        public Nullable<System.DateTime> Data_Registro { get; set; }
        public string Periodo_Desembaraco { get; set; }
        public string Data_Desembaraco { get; set; }
        public string Status_Followup { get; set; }
        public string Ref_Empresa { get; set; }
        public string Tipo_Processo { get; set; }
        public string Tipo_Declaracao { get; set; }
        public string Doc_Carga { get; set; }
        public string Doc_Master { get; set; }
        public string Faturas { get; set; }
        public string Pos { get; set; }
        public string Incoterm { get; set; }
        public string DI { get; set; }
        public string DDE { get; set; }
        public string TR { get; set; }
        public string Vencimento_TR { get; set; }
        public string RCR { get; set; }
        public Nullable<double> TR_VALOR_FOB { get; set; }
        public Nullable<double> TR_VALOR_CIF { get; set; }
        public Nullable<double> TR_VALOR_II { get; set; }
        public Nullable<double> TR_VALOR_IPI { get; set; }
        public Nullable<double> TR_VALOR_PIS { get; set; }
        public Nullable<double> TR_VALOR_CONFINS { get; set; }
        public Nullable<double> TR_VALOR_IMPOSTOS { get; set; }
        public Nullable<double> VALOR_FOB_CONSUMO { get; set; }
        public Nullable<double> VALOR_CIF_CONSUMO { get; set; }
        public Nullable<double> VALOR_FOB_ADMISSAO { get; set; }
        public Nullable<double> VALOR_CIF_ADMISSAO { get; set; }
        public Nullable<double> TOTAL_VALOR_FOB { get; set; }
        public Nullable<double> TOTAL_VALOR_CIF { get; set; }
        public Nullable<double> TOT_DEB_76 { get; set; }
        public Nullable<double> TOT_DEB_77 { get; set; }
        public Nullable<double> TOT_DEB_78 { get; set; }
        public Nullable<double> TOT_DEB_79 { get; set; }
        public Nullable<double> TOT_DEB_80 { get; set; }
        public Nullable<double> TOT_DEB_81 { get; set; }
        public Nullable<double> TOT_DEB_82 { get; set; }
        public Nullable<double> TOT_DEB_83 { get; set; }
        public Nullable<double> TOT_DEB_84 { get; set; }
        public Nullable<double> TOT_DEB_85 { get; set; }
        public Nullable<double> TOT_DEB_86 { get; set; }
        public Nullable<double> TOT_DEB_87 { get; set; }
        public Nullable<double> TOT_DEB_88 { get; set; }
        public Nullable<double> TOT_DEB_89 { get; set; }
        public Nullable<double> TOT_DEB_90 { get; set; }
        public Nullable<double> TOT_DEB_91 { get; set; }
        public Nullable<double> TOT_DEB_92 { get; set; }
        public Nullable<double> TOT_DEB_93 { get; set; }
        public Nullable<double> TOT_DEB_94 { get; set; }
        public Nullable<double> TOT_DEB_95 { get; set; }
        public Nullable<double> TOT_DEB_96 { get; set; }
        public Nullable<double> TOT_DEB_97 { get; set; }
        public Nullable<double> TOT_DEB_98 { get; set; }
        public Nullable<double> TOT_DEB_99 { get; set; }
        public Nullable<double> TOT_DEB_100 { get; set; }
        public Nullable<double> TOT_DEB_101 { get; set; }
        public Nullable<double> TOT_DEB_102 { get; set; }
        public Nullable<double> TOT_DEB_103 { get; set; }
        public Nullable<double> TOT_DEB_104 { get; set; }
        public Nullable<double> TOT_DEB_105 { get; set; }
        public Nullable<double> TOT_DEB_106 { get; set; }
        public Nullable<double> TOT_DEB_107 { get; set; }
        public Nullable<double> TOT_DEB_108 { get; set; }
        public Nullable<double> TOT_DEB_109 { get; set; }
        public Nullable<double> TOT_DEB_111 { get; set; }
        public Nullable<double> TOT_DEB_112 { get; set; }
        public Nullable<double> TOT_DEB_113 { get; set; }
        public Nullable<double> TOT_DEB_114 { get; set; }
        public Nullable<double> TOT_DEB_115 { get; set; }
        public Nullable<double> TOT_DEB_116 { get; set; }
        public Nullable<double> TOT_DEB_117 { get; set; }
        public Nullable<double> TOT_DEB_118 { get; set; }
        public Nullable<double> TOT_DEB_119 { get; set; }
        public Nullable<double> TOT_DEB_120 { get; set; }
        public Nullable<double> TOT_DEB_122 { get; set; }
        public Nullable<double> TOT_DEB_123 { get; set; }
        public Nullable<double> TOT_DEB_124 { get; set; }
        public Nullable<double> TOT_DEB_125 { get; set; }
        public Nullable<double> TOT_DEB_126 { get; set; }
        public Nullable<double> TOT_DEB_127 { get; set; }
        public Nullable<double> TOT_DEB_128 { get; set; }
        public Nullable<double> TOT_DEB_129 { get; set; }
        public Nullable<double> TOT_DEB_130 { get; set; }
        public Nullable<double> TOT_DEB_131 { get; set; }
        public Nullable<double> TOT_DEB_132 { get; set; }
        public Nullable<double> TOT_DEB_133 { get; set; }
        public Nullable<double> TOT_DEB_134 { get; set; }
        public Nullable<double> TOT_DEB_135 { get; set; }
        public Nullable<double> TOT_DEB_136 { get; set; }
        public Nullable<double> TOT_DEB_137 { get; set; }
        public Nullable<double> TOT_DEB_138 { get; set; }
        public Nullable<double> TOT_DEB_139 { get; set; }
        public Nullable<double> TOT_DEB_140 { get; set; }
        public Nullable<double> TOT_DEB_141 { get; set; }
        public Nullable<double> TOT_DEB_142 { get; set; }
        public Nullable<double> TOT_DEB_143 { get; set; }
        public Nullable<double> TOT_DEB_144 { get; set; }
        public Nullable<double> TOT_DEB_145 { get; set; }
        public Nullable<double> TOT_DEB_146 { get; set; }
        public Nullable<double> TOT_DEB_147 { get; set; }
        public Nullable<double> TOT_DEB_148 { get; set; }
        public Nullable<double> TOT_DEB_149 { get; set; }
        public Nullable<double> TOT_DEB_150 { get; set; }
        public Nullable<double> TOT_DEB_151 { get; set; }
        public Nullable<double> TOT_DEB_152 { get; set; }
        public Nullable<double> TOT_DEB_153 { get; set; }
        public Nullable<double> TOT_DEB_154 { get; set; }
        public Nullable<double> TOT_DEB_155 { get; set; }
        public Nullable<double> TOT_DEB_156 { get; set; }
        public Nullable<double> TOT_DEB_157 { get; set; }
        public Nullable<double> TOT_DEB_158 { get; set; }
        public Nullable<double> TOT_DEB_159 { get; set; }
        public Nullable<double> TOT_DEB_160 { get; set; }
        public Nullable<double> TOT_DEB_161 { get; set; }
        public Nullable<double> TOT_DEB_162 { get; set; }
        public Nullable<double> TOT_DEB_163 { get; set; }
        public Nullable<double> TOT_DEB_164 { get; set; }
        public Nullable<double> TOT_DEB_165 { get; set; }
        public Nullable<double> TOT_DEB_166 { get; set; }
        public Nullable<double> TOT_DEB_167 { get; set; }
        public Nullable<double> TOT_DEB_168 { get; set; }
        public Nullable<double> TOT_DEB_169 { get; set; }
        public Nullable<double> TOT_DEB_170 { get; set; }
        public Nullable<double> TOT_DEB_171 { get; set; }
        public Nullable<double> TOT_DEB_172 { get; set; }
        public Nullable<double> TOT_DEB_173 { get; set; }
        public Nullable<double> TOT_DEB_174 { get; set; }
        public Nullable<double> TOT_DEB_175 { get; set; }
        public Nullable<double> TOT_DEB_176 { get; set; }
        public Nullable<double> TOT_DEB_177 { get; set; }
        public Nullable<double> TOT_DEB_178 { get; set; }
        public Nullable<double> TOT_DEB_179 { get; set; }
        public Nullable<double> TOT_DEB_180 { get; set; }
        public Nullable<double> TOT_DEB_181 { get; set; }
        public Nullable<double> TOT_DEB_182 { get; set; }
        public Nullable<double> TOT_DEB_183 { get; set; }
        public Nullable<double> TOT_DEB_184 { get; set; }
        public Nullable<double> TOT_DEB_185 { get; set; }
        public Nullable<double> TOT_DEB_186 { get; set; }
        public Nullable<double> TOT_DEB_187 { get; set; }
        public Nullable<double> TOT_DEB_188 { get; set; }
        public Nullable<double> TOT_DEB_189 { get; set; }
        public Nullable<double> TOT_DEB_190 { get; set; }
        public Nullable<double> TOT_DEB_191 { get; set; }
        public Nullable<double> TOT_DEB_192 { get; set; }
        public Nullable<double> TOT_DEB_193 { get; set; }
        public Nullable<double> TOT_DEB_194 { get; set; }
        public Nullable<double> TOT_DEB_195 { get; set; }
        public Nullable<double> TOT_DEB_196 { get; set; }
        public Nullable<double> TOT_DEB_197 { get; set; }
        public Nullable<double> TOT_DEB_198 { get; set; }
        public Nullable<double> TOT_DEB_199 { get; set; }
        public Nullable<double> TOT_DEB_200 { get; set; }
        public Nullable<double> TOT_DEB_201 { get; set; }
        public Nullable<double> TOT_DEB_202 { get; set; }
        public Nullable<double> TOT_DEB_203 { get; set; }
        public Nullable<double> TOT_DEB_204 { get; set; }
        public Nullable<double> TOT_DEB_205 { get; set; }
        public Nullable<double> TOT_DEB_206 { get; set; }
        public Nullable<double> TOT_DEB_207 { get; set; }
        public Nullable<double> TOT_DEB_208 { get; set; }
        public Nullable<double> TOT_DEB_209 { get; set; }
        public Nullable<double> TOT_DEB_210 { get; set; }
        public Nullable<double> TOT_DEB_211 { get; set; }
        public Nullable<double> TOT_DEB_212 { get; set; }
        public Nullable<double> TOT_DEB_213 { get; set; }
        public Nullable<double> TOT_DEB_214 { get; set; }
        public Nullable<double> TOT_DEB_215 { get; set; }
        public Nullable<double> TOT_DEB_216 { get; set; }
        public Nullable<double> TOT_DEB_217 { get; set; }
        public Nullable<double> TOT_DEB_218 { get; set; }
        public Nullable<double> TOT_DEB_219 { get; set; }
        public Nullable<double> TOT_DEB_220 { get; set; }
        public Nullable<double> TOT_DEB_221 { get; set; }
        public Nullable<double> TOT_DEB_222 { get; set; }
        public Nullable<double> TOT_DEB_223 { get; set; }
        public Nullable<double> TOT_DEB_224 { get; set; }
        public Nullable<double> TOT_DEB_225 { get; set; }
        public Nullable<double> TOT_DEB_226 { get; set; }
        public Nullable<double> TOT_DEB_227 { get; set; }
        public Nullable<double> TOT_DEB_228 { get; set; }
        public Nullable<double> TOT_DEB_229 { get; set; }
        public Nullable<double> TOT_DEB_230 { get; set; }
        public Nullable<double> TOT_DEB_231 { get; set; }
        public Nullable<double> TOT_DEB_232 { get; set; }
        public Nullable<double> TOT_DEB_233 { get; set; }
        public Nullable<double> TOT_DEB_234 { get; set; }
        public Nullable<double> TOT_DEB_235 { get; set; }
        public Nullable<double> TOT_DEB_236 { get; set; }
        public Nullable<double> TOT_DEB_237 { get; set; }
        public Nullable<double> TOT_DEB_238 { get; set; }
        public Nullable<double> TOT_DEB_239 { get; set; }
        public Nullable<double> TOT_DEB_240 { get; set; }
        public Nullable<double> TOT_DEB_241 { get; set; }
        public Nullable<double> TOT_DEB_242 { get; set; }
        public Nullable<double> TOT_DEB_243 { get; set; }
        public Nullable<double> TOT_DEB_244 { get; set; }
        public Nullable<double> TOT_DEB_245 { get; set; }
        public Nullable<double> TOT_DEB_246 { get; set; }
        public Nullable<double> TOT_DEB_248 { get; set; }
        public Nullable<double> TOT_DEB_249 { get; set; }
        public Nullable<double> TOT_DEB_250 { get; set; }
        public Nullable<double> TOT_DEB_251 { get; set; }
        public Nullable<double> TOT_DEB_252 { get; set; }
        public Nullable<double> TOT_DEB_253 { get; set; }
        public Nullable<double> TOT_DEB_254 { get; set; }
        public Nullable<double> TOT_DEB_255 { get; set; }
        public Nullable<double> TOT_DEB_256 { get; set; }
        public Nullable<double> TOT_DEB_257 { get; set; }
        public Nullable<double> TOT_DEB_259 { get; set; }
        public Nullable<double> TOT_DEB_260 { get; set; }
        public Nullable<double> TOT_DEB_261 { get; set; }
        public Nullable<double> TOT_DEB_262 { get; set; }
        public Nullable<double> TOT_DEB_263 { get; set; }
        public Nullable<double> TOT_DEB_264 { get; set; }
        public Nullable<double> TOT_DEB_265 { get; set; }
        public Nullable<double> DEBITOS_CONSUMO { get; set; }
        public Nullable<double> DEBITOS_ADMISSAO { get; set; }
        public Nullable<double> DEBITOS_TOTAIS { get; set; }
        public Nullable<double> TOT_CRED_1 { get; set; }
        public Nullable<double> TOT_CRED_2 { get; set; }
        public Nullable<double> TOT_CRED_3 { get; set; }
        public Nullable<double> TOT_CRED_4 { get; set; }
        public Nullable<double> TOT_CRED_5 { get; set; }
        public Nullable<double> TOT_CRED_6 { get; set; }
        public Nullable<double> TOT_CRED_7 { get; set; }
        public Nullable<double> TOT_CRED_8 { get; set; }
        public Nullable<double> TOT_CRED_9 { get; set; }
        public Nullable<double> TOT_CRED_10 { get; set; }
        public Nullable<double> TOT_CRED_11 { get; set; }
        public Nullable<double> TOT_CRED_12 { get; set; }
        public Nullable<double> TOT_CRED_13 { get; set; }
        public Nullable<double> TOT_CRED_14 { get; set; }
        public Nullable<double> TOT_CRED_15 { get; set; }
        public Nullable<double> TOT_CRED_16 { get; set; }
        public Nullable<double> TOT_CRED_17 { get; set; }
        public Nullable<double> TOT_CRED_18 { get; set; }
        public Nullable<double> TOT_CRED_19 { get; set; }
        public Nullable<double> TOT_CRED_20 { get; set; }
        public Nullable<double> TOT_CRED_21 { get; set; }
        public Nullable<double> TOT_CRED_23 { get; set; }
        public Nullable<double> TOT_CRED_24 { get; set; }
        public Nullable<double> TOT_CRED_25 { get; set; }
        public Nullable<double> TOT_CRED_26 { get; set; }
        public Nullable<double> TOT_CRED_27 { get; set; }
        public Nullable<double> TOT_CRED_28 { get; set; }
        public Nullable<double> TOT_CRED_29 { get; set; }
        public Nullable<double> TOT_CRED_31 { get; set; }
        public Nullable<double> TOT_CRED_32 { get; set; }
        public Nullable<double> TOT_CRED_33 { get; set; }
        public Nullable<double> TOT_CRED_34 { get; set; }
        public Nullable<double> TOT_CRED_35 { get; set; }
        public Nullable<double> TOT_CRED_36 { get; set; }
        public Nullable<double> TOT_CRED_37 { get; set; }
        public Nullable<double> TOT_CRED_38 { get; set; }
        public Nullable<double> TOT_CRED_39 { get; set; }
        public Nullable<double> TOT_CRED_40 { get; set; }
        public Nullable<double> TOT_CRED_41 { get; set; }
        public Nullable<double> CREDITOS_TOTAIS { get; set; }
        public Nullable<double> SALDO { get; set; }
        public string NFISCAL { get; set; }
        public Nullable<System.DateTime> DATA_EMISSAO_NF { get; set; }
        public string NFISCAL_E { get; set; }
        public string CENTRO_CUSTO { get; set; }
        public string CODIGO_CONTABIL { get; set; }
        public string TABLE { get; set; }
        public string Numeromanifesto { get; set; }
        public Nullable<double> TAXA_DOLLAR { get; set; }
        public string CANAL { get; set; }
        public Nullable<System.DateTime> Data_Chegada_Despacho { get; set; }
        public string LOCAL_CONDICAO { get; set; }
        public string ULTIMO_FOLLOWUP { get; set; }
        public string Descricao_Produto_ing_Todos { get; set; }
        public string Descricao_Produto_Todos { get; set; }
        public string Embarcacao { get; set; }
        public Nullable<double> Peso_Bruto { get; set; }
        public Nullable<System.DateTime> Data_Embarque { get; set; }
        public string URF_Despacho { get; set; }
        public Nullable<double> ACERTO_II { get; set; }
        public Nullable<double> ACERTO_IPI { get; set; }
        public Nullable<double> ACERTO_ICMS { get; set; }
        public Nullable<double> ACERTO_FECP { get; set; }
        public Nullable<double> ACERTO_PIS { get; set; }
        public Nullable<double> ACERTO_COFINS { get; set; }
        public string ULTIMO_FOLLOWUP_ING { get; set; }
        public Nullable<double> TOT_DEB_266 { get; set; }
        public Nullable<double> TOT_DEB_267 { get; set; }
        public Nullable<double> TOT_DEB_268 { get; set; }
        public Nullable<double> TOT_DEB_269 { get; set; }
        public Nullable<double> TOT_DEB_270 { get; set; }
        public Nullable<double> TOT_DEB_271 { get; set; }
        public Nullable<double> TOT_DEB_272 { get; set; }
        public Nullable<double> TOT_DEB_273 { get; set; }
        public Nullable<double> TOT_DEB_274 { get; set; }
        public Nullable<double> TOT_DEB_275 { get; set; }
        public Nullable<double> TOT_DEB_277 { get; set; }
        public Nullable<double> TOT_DEB_278 { get; set; }
        public Nullable<double> TOT_CRED_30 { get; set; }
        public Nullable<double> TOT_DEB_281 { get; set; }
        public string Recinto_Alfandegario { get; set; }
        public Nullable<double> TOT_DEB_283 { get; set; }
        public Nullable<double> TOT_DEB_284 { get; set; }
        public Nullable<double> TOT_CRED_47 { get; set; }
        public Nullable<double> TOT_DEB_285 { get; set; }
        public Nullable<double> TOT_DEB_286 { get; set; }
        public Nullable<double> TOT_DEB_287 { get; set; }
        public Nullable<double> TOT_DEB_43 { get; set; }
    }
}
