//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resxIdioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resxIdioma() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.resxIdioma", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abertura.
        /// </summary>
        internal static string abertura {
            get {
                return ResourceManager.GetString("abertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        internal static string abrir {
            get {
                return ResourceManager.GetString("abrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceite.
        /// </summary>
        internal static string aceite {
            get {
                return ResourceManager.GetString("aceite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar.
        /// </summary>
        internal static string apagar {
            get {
                return ResourceManager.GetString("apagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armazéns.
        /// </summary>
        internal static string armazens {
            get {
                return ResourceManager.GetString("armazens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivos.
        /// </summary>
        internal static string arquivos {
            get {
                return ResourceManager.GetString("arquivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atas de reunião.
        /// </summary>
        internal static string atas_de_reuniao {
            get {
                return ResourceManager.GetString("atas_de_reuniao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atividade Econômica.
        /// </summary>
        internal static string atividade_economica {
            get {
                return ResourceManager.GetString("atividade_economica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        internal static string bairro {
            get {
                return ResourceManager.GetString("bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastros.
        /// </summary>
        internal static string cadastros {
            get {
                return ResourceManager.GetString("cadastros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        internal static string cep {
            get {
                return ResourceManager.GetString("cep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        internal static string cidade {
            get {
                return ResourceManager.GetString("cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string codigo {
            get {
                return ResourceManager.GetString("codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        internal static string complemento {
            get {
                return ResourceManager.GetString("complemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação.
        /// </summary>
        internal static string confirmacao {
            get {
                return ResourceManager.GetString("confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        internal static string confirmar {
            get {
                return ResourceManager.GetString("confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultas.
        /// </summary>
        internal static string consultas {
            get {
                return ResourceManager.GetString("consultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controles.
        /// </summary>
        internal static string controles {
            get {
                return ResourceManager.GetString("controles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados da reunião.
        /// </summary>
        internal static string dados_da_reuniao {
            get {
                return ResourceManager.GetString("dados_da_reuniao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data do aceite.
        /// </summary>
        internal static string data_do_aceite {
            get {
                return ResourceManager.GetString("data_do_aceite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descricao.
        /// </summary>
        internal static string db_descricao {
            get {
                return ResourceManager.GetString("db_descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string descricao {
            get {
                return ResourceManager.GetString("descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição Inglês.
        /// </summary>
        internal static string descricao_ing {
            get {
                return ResourceManager.GetString("descricao_ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string editar {
            get {
                return ResourceManager.GetString("editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        internal static string endereco {
            get {
                return ResourceManager.GetString("endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        internal static string entrar {
            get {
                return ResourceManager.GetString("entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string enviar {
            get {
                return ResourceManager.GetString("enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string erro {
            get {
                return ResourceManager.GetString("erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportação.
        /// </summary>
        internal static string exportacao {
            get {
                return ResourceManager.GetString("exportacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportador.
        /// </summary>
        internal static string Exportador {
            get {
                return ResourceManager.GetString("Exportador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatura.
        /// </summary>
        internal static string Fatura {
            get {
                return ResourceManager.GetString("Fatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        internal static string fechar {
            get {
                return ResourceManager.GetString("fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar por.
        /// </summary>
        internal static string filtrar_por {
            get {
                return ResourceManager.GetString("filtrar_por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financeiro.
        /// </summary>
        internal static string financeiro {
            get {
                return ResourceManager.GetString("financeiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos.
        /// </summary>
        internal static string grupos {
            get {
                return ResourceManager.GetString("grupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string idioma {
            get {
                return ResourceManager.GetString("idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importador.
        /// </summary>
        internal static string importador {
            get {
                return ResourceManager.GetString("importador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir.
        /// </summary>
        internal static string incluir {
            get {
                return ResourceManager.GetString("incluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação.
        /// </summary>
        internal static string informacao {
            get {
                return ResourceManager.GetString("informacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso não autorizado!.
        /// </summary>
        internal static string msg_acesso_nao_autorizado {
            get {
                return ResourceManager.GetString("msg_acesso_nao_autorizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente apagar o registro selecionado?.
        /// </summary>
        internal static string msg_apagar {
            get {
                return ResourceManager.GetString("msg_apagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo é obrigatório.
        /// </summary>
        internal static string msg_campo_obrigatorio {
            get {
                return ResourceManager.GetString("msg_campo_obrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibe nas informações complemetares.
        /// </summary>
        internal static string msg_exibe_info_complentares {
            get {
                return ResourceManager.GetString("msg_exibe_info_complentares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro durante a gravação!.
        /// </summary>
        internal static string msg_gravadoErro {
            get {
                return ResourceManager.GetString("msg_gravadoErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro gravado com sucesso!.
        /// </summary>
        internal static string msg_gravadoOk {
            get {
                return ResourceManager.GetString("msg_gravadoOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        internal static string nao {
            get {
                return ResourceManager.GetString("nao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string nome {
            get {
                return ResourceManager.GetString("nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome completo.
        /// </summary>
        internal static string nome_completo {
            get {
                return ResourceManager.GetString("nome_completo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        internal static string numero {
            get {
                return ResourceManager.GetString("numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá.
        /// </summary>
        internal static string ola {
            get {
                return ResourceManager.GetString("ola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacional.
        /// </summary>
        internal static string operacional {
            get {
                return ResourceManager.GetString("operacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string pais {
            get {
                return ResourceManager.GetString("pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participante.
        /// </summary>
        internal static string participante {
            get {
                return ResourceManager.GetString("participante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar.
        /// </summary>
        internal static string pesquisar {
            get {
                return ResourceManager.GetString("pesquisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processos.
        /// </summary>
        internal static string processos {
            get {
                return ResourceManager.GetString("processos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procuradores.
        /// </summary>
        internal static string procuradores {
            get {
                return ResourceManager.GetString("procuradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produtos.
        /// </summary>
        internal static string produtos {
            get {
                return ResourceManager.GetString("produtos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão social.
        /// </summary>
        internal static string razao_social {
            get {
                return ResourceManager.GetString("razao_social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        internal static string registro {
            get {
                return ResourceManager.GetString("registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatório.
        /// </summary>
        internal static string relatorio {
            get {
                return ResourceManager.GetString("relatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        internal static string responsavel {
            get {
                return ResourceManager.GetString("responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RH.
        /// </summary>
        internal static string rh {
            get {
                return ResourceManager.GetString("rh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string sair {
            get {
                return ResourceManager.GetString("sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        internal static string salvar {
            get {
                return ResourceManager.GetString("salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seja bem vindo.
        /// </summary>
        internal static string seja_bem_vindo {
            get {
                return ResourceManager.GetString("seja_bem_vindo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string senha {
            get {
                return ResourceManager.GetString("senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        internal static string sim {
            get {
                return ResourceManager.GetString("sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        internal static string sistema {
            get {
                return ResourceManager.GetString("sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tela de Acesso.
        /// </summary>
        internal static string tela_de_acesso {
            get {
                return ResourceManager.GetString("tela_de_acesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        internal static string telefone {
            get {
                return ResourceManager.GetString("telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        internal static string tema {
            get {
                return ResourceManager.GetString("tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string tipo {
            get {
                return ResourceManager.GetString("tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos os direitos reservados.
        /// </summary>
        internal static string todos_direitos_reservados {
            get {
                return ResourceManager.GetString("todos_direitos_reservados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        internal static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuários.
        /// </summary>
        internal static string usuarios {
            get {
                return ResourceManager.GetString("usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        internal static string voltar {
            get {
                return ResourceManager.GetString("voltar", resourceCulture);
            }
        }
    }
}
