//////////////////////////
//Generated by XSD2Class.
//////////////////////////
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.IO;

namespace MS2000.Desktop.Classes.SiscomexTransmissao
{
    public partial class adicaoDestaqueTarifario
    {

        private string _codigoassuntovinculado;
        private string _dataanoatovinculado;
        private string _numeroatovinculado;
        private string _numeroexatovinculado;
        private string _siglaorgaoatovinculado;
        private string _siglatipoatovinculado;

        public string codigoAssuntoVinculado
        {
            get { return _codigoassuntovinculado; }
            set { _codigoassuntovinculado = value; }
        }

        public string dataAnoAtoVinculado
        {
            get { return _dataanoatovinculado; }
            set { _dataanoatovinculado = value; }
        }

        public string numeroAtoVinculado
        {
            get { return _numeroatovinculado; }
            set { _numeroatovinculado = value; }
        }

        public string numeroEXAtoVinculado
        {
            get { return _numeroexatovinculado; }
            set { _numeroexatovinculado = value; }
        }

        public string siglaOrgaoAtoVinculado
        {
            get { return _siglaorgaoatovinculado; }
            set { _siglaorgaoatovinculado = value; }
        }

        public string siglaTipoAtoVinculado
        {
            get { return _siglatipoatovinculado; }
            set { _siglatipoatovinculado = value; }
        }

        public string ToXML()
        {
            XmlSerializer serializer = new XmlSerializer(typeof(adicaoDestaqueTarifario));
            MemoryStream ms = new System.IO.MemoryStream();
            serializer.Serialize(ms, this);
            StreamReader sr = new System.IO.StreamReader(ms);
            return sr.ReadToEnd();
        }
    }
}