//////////////////////////
//Generated by XSD2Class.
//////////////////////////
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.IO;

namespace MS2000.Desktop.Classes.SiscomexTransmissao
{
    public partial class adicaoEspecificacaoMercadoriaValoracaoAduaneira
    {

        private string _codigoabrangenciancm;
        private string _codigoatributoncm;
        private string _codigoespecificacaoncm;

        public string codigoAbrangenciaNCM
        {
            get { return _codigoabrangenciancm; }
            set { _codigoabrangenciancm = value; }
        }

        public string codigoAtributoNCM
        {
            get { return _codigoatributoncm; }
            set { _codigoatributoncm = value; }
        }

        public string codigoEspecificacaoNCM
        {
            get { return _codigoespecificacaoncm; }
            set { _codigoespecificacaoncm = value; }
        }

        public string ToXML()
        {
            XmlSerializer serializer = new XmlSerializer(typeof(adicaoEspecificacaoMercadoriaValoracaoAduaneira));
            MemoryStream ms = new System.IO.MemoryStream();
            serializer.Serialize(ms, this);
            StreamReader sr = new System.IO.StreamReader(ms);
            return sr.ReadToEnd();
        }
    }
}