//////////////////////////
//Generated by XSD2Class.
//////////////////////////
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.IO;

namespace MS2000.Desktop.Classes.SiscomexTransmissao
{
    public partial class adicao
    {

        private adicaoAcrescimoValorAduaneiro _acrescimo;
        private string _codigoacordoaladi;
        private string _codigoaplicacaomercadoria;
        private string _codigoausenciafabricante;
        private string _codigocoberturacambial;
        private string _codigofundamentolegalreduzido;
        private string _codigofundamentolegalregime;
        private string _codigofundamentolegalregimepiscofins;
        private string _codigoincotermsvenda;
        private string _codigomercadorianbmsh;
        private string _codigomercadoriancm;
        private string _codigomercadorianaladincc;
        private string _codigomercadorianaladish;
        private string _codigometodovaloracao;
        private string _codigomoedafretemercadoria;
        private string _codigomoedanegociada;
        private string _codigomoedaseguromercadoria;
        private string _codigomotivoadmissaotemporaria;
        private string _codigomotivosemcobertura;
        private string _codigoorgaofinanciamentointernacional;
        private string _codigopaisaquisicaomercadoria;
        private string _codigopaisorigemmercadoria;
        private string _codigopaisprocedenciamercadoria;
        private string _codigoregimetriburariopiscofins;
        private string _codigoregimetributacao;
        private string _codigotipoacordotarifario;
        private string _codigourfentradamercadoria;
        private string _codigoviatransporte;
        private string _codigovinculoimportadorexportador;
        private adicaoDeducaoValorAduaneiro _deducao;
        private adicaoDestaqueNCM _destaque;
        private adicaoDocumentoVinculado _documento;
        private adicaoDocumentoMercosul _documentomercosul;
        private string _enderecocidadefabricante;
        private string _enderecocidadefornecedorestrangeiro;
        private string _enderecocomplementofabricante;
        private string _enderecocomplementofornecedorestrangeiro;
        private string _enderecoestadofabricante;
        private string _enderecoestadofornecedorestrangeiro;
        private string _enderecologradourofornecedorestrangeiro;
        private string _enderecologradourofabricante;
        private string _endereconumerofabricante;
        private string _endereconumerofornecedorestrangeiro;
        private string _indicadorbemencomenda;
        private string _indicadormaterialusado;
        private string _indicadormultimodal;
        private string _indicadortipocertificado;
        private adicaoDetalhamentoMercadoria _mercadoria;
        private string _nomefabricantemercadoria;
        private string _nomefornecedorestrangeiro;
        private string _nomelocalcondicaovenda;
        private string _numeroadicao;
        private string _numerodocumentoreducao;
        private string _numeroidentificacaoli;
        private string _numerorof;
        private string _percentualcoeficientereducaoii;
        private string _pesoliquidomercadoria;
        private string _quantidadeunidadeestatistica;
        private adicaoDestaqueTarifario _tarifa;
        private string _textocomplementovaloraduaneiro;
        private adicaoTributo _tributo;
        private string _valoraliquotaicms;
        private string _valorcalculodcrdolar;
        private string _valorfinanciadosuperior360;
        private string _valorfretemercadoriamoedanacional;
        private string _valorfretemercadoriamoedanegociada;
        private string _valoriicalculadodcrmoedanacional;
        private string _valoriidevidozfm;
        private string _valoriiareceberzfm;
        private string _valormercadoriacondicaovenda;
        private string _valormercadoriaembarquemoedanacional;
        private string _valormercadoriavendamoedanacional;
        private string _valorseguromercadoriamoedanacional;
        private string _valorseguromercadoriamoedanegociada;
        private adicaoEspecificacaoMercadoriaValoracaoAduaneira _valoracaoaduaneira;

        public adicao()
        {
            _acrescimo = new adicaoAcrescimoValorAduaneiro();
            _deducao = new adicaoDeducaoValorAduaneiro();
            _destaque = new adicaoDestaqueNCM();
            _documento = new adicaoDocumentoVinculado();
            _documentomercosul = new adicaoDocumentoMercosul();
            _mercadoria = new adicaoDetalhamentoMercadoria();
            _tarifa = new adicaoDestaqueTarifario();
            _tributo = new adicaoTributo();
            _valoracaoaduaneira = new adicaoEspecificacaoMercadoriaValoracaoAduaneira();
        }

        public adicaoAcrescimoValorAduaneiro acrescimo
        {
            get { return _acrescimo; }
            set { _acrescimo = value; }
        }

        public string codigoAcordoAladi
        {
            get { return _codigoacordoaladi; }
            set { _codigoacordoaladi = value; }
        }

        public string codigoAplicacaoMercadoria
        {
            get { return _codigoaplicacaomercadoria; }
            set { _codigoaplicacaomercadoria = value; }
        }

        public string codigoAusenciaFabricante
        {
            get { return _codigoausenciafabricante; }
            set { _codigoausenciafabricante = value; }
        }

        public string codigoCoberturaCambial
        {
            get { return _codigocoberturacambial; }
            set { _codigocoberturacambial = value; }
        }

        public string codigoFundamentoLegalReduzido
        {
            get { return _codigofundamentolegalreduzido; }
            set { _codigofundamentolegalreduzido = value; }
        }

        public string codigoFundamentoLegalRegime
        {
            get { return _codigofundamentolegalregime; }
            set { _codigofundamentolegalregime = value; }
        }

        public string codigoFundamentoLegalRegimePisCofins
        {
            get { return _codigofundamentolegalregimepiscofins; }
            set { _codigofundamentolegalregimepiscofins = value; }
        }

        public string codigoIncotermsVenda
        {
            get { return _codigoincotermsvenda; }
            set { _codigoincotermsvenda = value; }
        }

        public string codigoMercadoriaNBMSH
        {
            get { return _codigomercadorianbmsh; }
            set { _codigomercadorianbmsh = value; }
        }

        public string codigoMercadoriaNCM
        {
            get { return _codigomercadoriancm; }
            set { _codigomercadoriancm = value; }
        }

        public string codigoMercadoriaNaladiNCC
        {
            get { return _codigomercadorianaladincc; }
            set { _codigomercadorianaladincc = value; }
        }

        public string codigoMercadoriaNaladiSH
        {
            get { return _codigomercadorianaladish; }
            set { _codigomercadorianaladish = value; }
        }

        public string codigoMetodoValoracao
        {
            get { return _codigometodovaloracao; }
            set { _codigometodovaloracao = value; }
        }

        public string codigoMoedaFreteMercadoria
        {
            get { return _codigomoedafretemercadoria; }
            set { _codigomoedafretemercadoria = value; }
        }

        public string codigoMoedaNegociada
        {
            get { return _codigomoedanegociada; }
            set { _codigomoedanegociada = value; }
        }

        public string codigoMoedaSeguroMercadoria
        {
            get { return _codigomoedaseguromercadoria; }
            set { _codigomoedaseguromercadoria = value; }
        }

        public string codigoMotivoAdmissaoTemporaria
        {
            get { return _codigomotivoadmissaotemporaria; }
            set { _codigomotivoadmissaotemporaria = value; }
        }

        public string codigoMotivoSemCobertura
        {
            get { return _codigomotivosemcobertura; }
            set { _codigomotivosemcobertura = value; }
        }

        public string codigoOrgaoFinanciamentoInternacional
        {
            get { return _codigoorgaofinanciamentointernacional; }
            set { _codigoorgaofinanciamentointernacional = value; }
        }

        public string codigoPaisAquisicaoMercadoria
        {
            get { return _codigopaisaquisicaomercadoria; }
            set { _codigopaisaquisicaomercadoria = value; }
        }

        public string codigoPaisOrigemMercadoria
        {
            get { return _codigopaisorigemmercadoria; }
            set { _codigopaisorigemmercadoria = value; }
        }

        public string codigoPaisProcedenciaMercadoria
        {
            get { return _codigopaisprocedenciamercadoria; }
            set { _codigopaisprocedenciamercadoria = value; }
        }

        public string codigoRegimeTriburarioPisCofins
        {
            get { return _codigoregimetriburariopiscofins; }
            set { _codigoregimetriburariopiscofins = value; }
        }

        public string codigoRegimeTributacao
        {
            get { return _codigoregimetributacao; }
            set { _codigoregimetributacao = value; }
        }

        public string codigoTipoAcordoTarifario
        {
            get { return _codigotipoacordotarifario; }
            set { _codigotipoacordotarifario = value; }
        }

        public string codigoURFEntradaMercadoria
        {
            get { return _codigourfentradamercadoria; }
            set { _codigourfentradamercadoria = value; }
        }

        public string codigoViaTransporte
        {
            get { return _codigoviatransporte; }
            set { _codigoviatransporte = value; }
        }

        public string codigoVinculoImportadorExportador
        {
            get { return _codigovinculoimportadorexportador; }
            set { _codigovinculoimportadorexportador = value; }
        }

        public adicaoDeducaoValorAduaneiro deducao
        {
            get { return _deducao; }
            set { _deducao = value; }
        }

        public adicaoDestaqueNCM destaque
        {
            get { return _destaque; }
            set { _destaque = value; }
        }

        public adicaoDocumentoVinculado documento
        {
            get { return _documento; }
            set { _documento = value; }
        }

        public adicaoDocumentoMercosul documentoMercosul
        {
            get { return _documentomercosul; }
            set { _documentomercosul = value; }
        }

        public string enderecoCidadeFabricante
        {
            get { return _enderecocidadefabricante; }
            set { _enderecocidadefabricante = value; }
        }

        public string enderecoCidadeFornecedorEstrangeiro
        {
            get { return _enderecocidadefornecedorestrangeiro; }
            set { _enderecocidadefornecedorestrangeiro = value; }
        }

        public string enderecoComplementoFabricante
        {
            get { return _enderecocomplementofabricante; }
            set { _enderecocomplementofabricante = value; }
        }

        public string enderecoComplementoFornecedorEstrangeiro
        {
            get { return _enderecocomplementofornecedorestrangeiro; }
            set { _enderecocomplementofornecedorestrangeiro = value; }
        }

        public string enderecoEstadoFabricante
        {
            get { return _enderecoestadofabricante; }
            set { _enderecoestadofabricante = value; }
        }

        public string enderecoEstadoFornecedorEstrangeiro
        {
            get { return _enderecoestadofornecedorestrangeiro; }
            set { _enderecoestadofornecedorestrangeiro = value; }
        }

        public string enderecoLogradouroFornecedorEstrangeiro
        {
            get { return _enderecologradourofornecedorestrangeiro; }
            set { _enderecologradourofornecedorestrangeiro = value; }
        }

        public string enderecoLogradouroFabricante
        {
            get { return _enderecologradourofabricante; }
            set { _enderecologradourofabricante = value; }
        }

        public string enderecoNumeroFabricante
        {
            get { return _endereconumerofabricante; }
            set { _endereconumerofabricante = value; }
        }

        public string enderecoNumeroFornecedorEstrangeiro
        {
            get { return _endereconumerofornecedorestrangeiro; }
            set { _endereconumerofornecedorestrangeiro = value; }
        }

        public string indicadorBemEncomenda
        {
            get { return _indicadorbemencomenda; }
            set { _indicadorbemencomenda = value; }
        }

        public string indicadorMaterialUsado
        {
            get { return _indicadormaterialusado; }
            set { _indicadormaterialusado = value; }
        }

        public string indicadorMultimodal
        {
            get { return _indicadormultimodal; }
            set { _indicadormultimodal = value; }
        }

        public string indicadorTipoCertificado
        {
            get { return _indicadortipocertificado; }
            set { _indicadortipocertificado = value; }
        }

        public adicaoDetalhamentoMercadoria mercadoria
        {
            get { return _mercadoria; }
            set { _mercadoria = value; }
        }

        public string nomeFabricanteMercadoria
        {
            get { return _nomefabricantemercadoria; }
            set { _nomefabricantemercadoria = value; }
        }

        public string nomeFornecedorEstrangeiro
        {
            get { return _nomefornecedorestrangeiro; }
            set { _nomefornecedorestrangeiro = value; }
        }

        public string nomeLocalCondicaoVenda
        {
            get { return _nomelocalcondicaovenda; }
            set { _nomelocalcondicaovenda = value; }
        }

        public string numeroAdicao
        {
            get { return _numeroadicao; }
            set { _numeroadicao = value; }
        }

        public string numeroDocumentoReducao
        {
            get { return _numerodocumentoreducao; }
            set { _numerodocumentoreducao = value; }
        }

        public string numeroIdentificacaoLI
        {
            get { return _numeroidentificacaoli; }
            set { _numeroidentificacaoli = value; }
        }

        public string numeroROF
        {
            get { return _numerorof; }
            set { _numerorof = value; }
        }

        public string percentualCoeficienteReducaoII
        {
            get { return _percentualcoeficientereducaoii; }
            set { _percentualcoeficientereducaoii = value; }
        }

        public string pesoLiquidoMercadoria
        {
            get { return _pesoliquidomercadoria; }
            set { _pesoliquidomercadoria = value; }
        }

        public string quantidadeUnidadeEstatistica
        {
            get { return _quantidadeunidadeestatistica; }
            set { _quantidadeunidadeestatistica = value; }
        }

        public adicaoDestaqueTarifario tarifa
        {
            get { return _tarifa; }
            set { _tarifa = value; }
        }

        public string textoComplementoValorAduaneiro
        {
            get { return _textocomplementovaloraduaneiro; }
            set { _textocomplementovaloraduaneiro = value; }
        }

        public adicaoTributo tributo
        {
            get { return _tributo; }
            set { _tributo = value; }
        }

        public string valorAliquotaIcms
        {
            get { return _valoraliquotaicms; }
            set { _valoraliquotaicms = value; }
        }

        public string valorCalculoDCRDolar
        {
            get { return _valorcalculodcrdolar; }
            set { _valorcalculodcrdolar = value; }
        }

        public string valorFinanciadoSuperior360
        {
            get { return _valorfinanciadosuperior360; }
            set { _valorfinanciadosuperior360 = value; }
        }

        public string valorFreteMercadoriaMoedaNacional
        {
            get { return _valorfretemercadoriamoedanacional; }
            set { _valorfretemercadoriamoedanacional = value; }
        }

        public string valorFreteMercadoriaMoedaNegociada
        {
            get { return _valorfretemercadoriamoedanegociada; }
            set { _valorfretemercadoriamoedanegociada = value; }
        }

        public string valorIICalculadoDCRMoedaNacional
        {
            get { return _valoriicalculadodcrmoedanacional; }
            set { _valoriicalculadodcrmoedanacional = value; }
        }

        public string valorIIDevidoZFM
        {
            get { return _valoriidevidozfm; }
            set { _valoriidevidozfm = value; }
        }

        public string valorIIaReceberZFM
        {
            get { return _valoriiareceberzfm; }
            set { _valoriiareceberzfm = value; }
        }

        public string valorMercadoriaCondicaoVenda
        {
            get { return _valormercadoriacondicaovenda; }
            set { _valormercadoriacondicaovenda = value; }
        }

        public string valorMercadoriaEmbarqueMoedaNacional
        {
            get { return _valormercadoriaembarquemoedanacional; }
            set { _valormercadoriaembarquemoedanacional = value; }
        }

        public string valorMercadoriaVendaMoedaNacional
        {
            get { return _valormercadoriavendamoedanacional; }
            set { _valormercadoriavendamoedanacional = value; }
        }

        public string valorSeguroMercadoriaMoedaNacional
        {
            get { return _valorseguromercadoriamoedanacional; }
            set { _valorseguromercadoriamoedanacional = value; }
        }

        public string valorSeguroMercadoriaMoedaNegociada
        {
            get { return _valorseguromercadoriamoedanegociada; }
            set { _valorseguromercadoriamoedanegociada = value; }
        }

        public adicaoEspecificacaoMercadoriaValoracaoAduaneira valoracaoAduaneira
        {
            get { return _valoracaoaduaneira; }
            set { _valoracaoaduaneira = value; }
        }

        public string ToXML()
        {
            XmlSerializer serializer = new XmlSerializer(typeof(adicao));
            MemoryStream ms = new System.IO.MemoryStream();
            serializer.Serialize(ms, this);
            StreamReader sr = new System.IO.StreamReader(ms);
            return sr.ReadToEnd();
        }
    }
}