//////////////////////////
//Generated by XSD2Class.
//////////////////////////
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.IO;

namespace MS2000.Desktop.Classes.SiscomexTransmissao
{
    public partial class adicaoAcrescimoValorAduaneiro
    {

        private string _codigometodoacrescimovalor;
        private string _codigomoedanegociadaacrescimo;
        private string _valoracrescimomoedanacional;
        private string _valoracrescimomoedanegociada;

        public string codigoMetodoAcrescimoValor
        {
            get { return _codigometodoacrescimovalor; }
            set { _codigometodoacrescimovalor = value; }
        }

        public string codigoMoedaNegociadaAcrescimo
        {
            get { return _codigomoedanegociadaacrescimo; }
            set { _codigomoedanegociadaacrescimo = value; }
        }

        public string valorAcrescimoMoedaNacional
        {
            get { return _valoracrescimomoedanacional; }
            set { _valoracrescimomoedanacional = value; }
        }

        public string valorAcrescimoMoedaNegociada
        {
            get { return _valoracrescimomoedanegociada; }
            set { _valoracrescimomoedanegociada = value; }
        }

        public string ToXML()
        {
            XmlSerializer serializer = new XmlSerializer(typeof(adicaoAcrescimoValorAduaneiro));
            MemoryStream ms = new System.IO.MemoryStream();
            serializer.Serialize(ms, this);
            StreamReader sr = new System.IO.StreamReader(ms);
            return sr.ReadToEnd();
        }
    }
}