//////////////////////////
//Generated by XSD2Class.
//////////////////////////
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.IO;

namespace MS2000.Desktop.Classes.SiscomexTransmissao
{
    public partial class adicaoDocumentoMercosul
    {

        private string _codigopaiscertificado;
        private string _numerodeadmercosul;
        private string _numerodicertificado;
        private string _numeroitemcertificado;
        private string _numeroreadfinal;
        private string _numeroreadinicial;
        private string _quantidadeunidademercosul;

        public string codigoPaisCertificado
        {
            get { return _codigopaiscertificado; }
            set { _codigopaiscertificado = value; }
        }

        public string numeroDEADMercosul
        {
            get { return _numerodeadmercosul; }
            set { _numerodeadmercosul = value; }
        }

        public string numeroDICertificado
        {
            get { return _numerodicertificado; }
            set { _numerodicertificado = value; }
        }

        public string numeroItemCertificado
        {
            get { return _numeroitemcertificado; }
            set { _numeroitemcertificado = value; }
        }

        public string numeroREADFinal
        {
            get { return _numeroreadfinal; }
            set { _numeroreadfinal = value; }
        }

        public string numeroREADInicial
        {
            get { return _numeroreadinicial; }
            set { _numeroreadinicial = value; }
        }

        public string quantidadeUnidadeMercosul
        {
            get { return _quantidadeunidademercosul; }
            set { _quantidadeunidademercosul = value; }
        }

        public string ToXML()
        {
            XmlSerializer serializer = new XmlSerializer(typeof(adicaoDocumentoMercosul));
            MemoryStream ms = new System.IO.MemoryStream();
            serializer.Serialize(ms, this);
            StreamReader sr = new System.IO.StreamReader(ms);
            return sr.ReadToEnd();
        }
    }
}