//////////////////////////
//Generated by XSD2Class.
//////////////////////////
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.IO;

namespace MS2000.Desktop.Classes.SiscomexTransmissao
{
    public partial class adicaoTributo
    {

        private string _codigoreceitaimposto;
        private string _codigotipoaliquotaipt;
        private string _codigotipobeneficioipi;
        private string _codigotipodireito;
        private string _codigotiporecipiente;
        private string _nomeunidadeespecificaaliquotaipt;
        private string _numeronotacomplementartipi;
        private string _percentualaliquotaacordotarifario;
        private string _percentualaliquotanormaladval;
        private string _percentualaliquotareduzida;
        private string _percentualreducaoipt;
        private string _quantidademlrecipiente;
        private string _quantidademercadoriaunidadealiquotaespecifica;
        private string _valoraliquotaespecificaipt;
        private string _valorbasecalculoadval;
        private string _valorcalculadoiiactarifario;
        private string _valorcalculoiptespecifica;
        private string _valorcalculoiptadval;
        private string _valoriptarecolher;
        private string _valorimpostodevido;

        public string codigoReceitaImposto
        {
            get { return _codigoreceitaimposto; }
            set { _codigoreceitaimposto = value; }
        }

        public string codigoTipoAliquotaIPT
        {
            get { return _codigotipoaliquotaipt; }
            set { _codigotipoaliquotaipt = value; }
        }

        public string codigoTipoBeneficioIPI
        {
            get { return _codigotipobeneficioipi; }
            set { _codigotipobeneficioipi = value; }
        }

        public string codigoTipoDireito
        {
            get { return _codigotipodireito; }
            set { _codigotipodireito = value; }
        }

        public string codigoTipoRecipiente
        {
            get { return _codigotiporecipiente; }
            set { _codigotiporecipiente = value; }
        }

        public string nomeUnidadeEspecificaAliquotaIPT
        {
            get { return _nomeunidadeespecificaaliquotaipt; }
            set { _nomeunidadeespecificaaliquotaipt = value; }
        }

        public string numeroNotaComplementarTIPI
        {
            get { return _numeronotacomplementartipi; }
            set { _numeronotacomplementartipi = value; }
        }

        public string percentualAliquotaAcordoTarifario
        {
            get { return _percentualaliquotaacordotarifario; }
            set { _percentualaliquotaacordotarifario = value; }
        }

        public string percentualAliquotaNormalAdval
        {
            get { return _percentualaliquotanormaladval; }
            set { _percentualaliquotanormaladval = value; }
        }

        public string percentualAliquotaReduzida
        {
            get { return _percentualaliquotareduzida; }
            set { _percentualaliquotareduzida = value; }
        }

        public string percentualReducaoIPT
        {
            get { return _percentualreducaoipt; }
            set { _percentualreducaoipt = value; }
        }

        public string quantidadeMLRecipiente
        {
            get { return _quantidademlrecipiente; }
            set { _quantidademlrecipiente = value; }
        }

        public string quantidadeMercadoriaUnidadeAliquotaEspecifica
        {
            get { return _quantidademercadoriaunidadealiquotaespecifica; }
            set { _quantidademercadoriaunidadealiquotaespecifica = value; }
        }

        public string valorAliquotaEspecificaIPT
        {
            get { return _valoraliquotaespecificaipt; }
            set { _valoraliquotaespecificaipt = value; }
        }

        public string valorBaseCalculoAdval
        {
            get { return _valorbasecalculoadval; }
            set { _valorbasecalculoadval = value; }
        }

        public string valorCalculadoIIACTarifario
        {
            get { return _valorcalculadoiiactarifario; }
            set { _valorcalculadoiiactarifario = value; }
        }

        public string valorCalculoIPTEspecifica
        {
            get { return _valorcalculoiptespecifica; }
            set { _valorcalculoiptespecifica = value; }
        }

        public string valorCalculoIptAdval
        {
            get { return _valorcalculoiptadval; }
            set { _valorcalculoiptadval = value; }
        }

        public string valorIPTaRecolher
        {
            get { return _valoriptarecolher; }
            set { _valoriptarecolher = value; }
        }

        public string valorImpostoDevido
        {
            get { return _valorimpostodevido; }
            set { _valorimpostodevido = value; }
        }

        public string ToXML()
        {
            XmlSerializer serializer = new XmlSerializer(typeof(adicaoTributo));
            MemoryStream ms = new System.IO.MemoryStream();
            serializer.Serialize(ms, this);
            StreamReader sr = new System.IO.StreamReader(ms);
            return sr.ReadToEnd();
        }
    }
}