//////////////////////////
//Generated by XSD2Class.
//////////////////////////
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.IO;

namespace MS2000.Desktop.Classes.SiscomexTransmissao
{
    public partial class documentoInstrucaoDespacho
    {

        private string _codigotipodocumentoinstrucaodespacho;
        private string _numerodocumentoinstrucaodespacho;

        public string codigoTipoDocumentoInstrucaoDespacho
        {
            get { return _codigotipodocumentoinstrucaodespacho; }
            set { _codigotipodocumentoinstrucaodespacho = value; }
        }

        public string numeroDocumentoInstrucaoDespacho
        {
            get { return _numerodocumentoinstrucaodespacho; }
            set { _numerodocumentoinstrucaodespacho = value; }
        }

        public string ToXML()
        {
            XmlSerializer serializer = new XmlSerializer(typeof(documentoInstrucaoDespacho));
            MemoryStream ms = new System.IO.MemoryStream();
            serializer.Serialize(ms, this);
            StreamReader sr = new System.IO.StreamReader(ms);
            return sr.ReadToEnd();
        }
    }
}