//////////////////////////
//Generated by XSD2Class.
//////////////////////////
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.IO;

namespace MS2000.Desktop.Classes.SiscomexTransmissao
{
    public partial class embalagemCarga
    {

        private string _codigotipoembalagemcarga;
        private string _quantidadevolumecarga;

        public string codigoTipoEmbalagemCarga
        {
            get { return _codigotipoembalagemcarga; }
            set { _codigotipoembalagemcarga = value; }
        }

        public string quantidadeVolumeCarga
        {
            get { return _quantidadevolumecarga; }
            set { _quantidadevolumecarga = value; }
        }

        public string ToXML()
        {
            XmlSerializer serializer = new XmlSerializer(typeof(embalagemCarga));
            MemoryStream ms = new System.IO.MemoryStream();
            serializer.Serialize(ms, this);
            StreamReader sr = new System.IO.StreamReader(ms);
            return sr.ReadToEnd();
        }
    }
}