//////////////////////////
//Generated by XSD2Class.
//////////////////////////
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.IO;

namespace MS2000.Desktop.Classes.SiscomexTransmissao
{
    public partial class informacaoMercosul
    {

        private string _numerodemercosul;
        private string _numerorefinal;
        private string _numeroreinicial;

        public string numeroDEMercosul
        {
            get { return _numerodemercosul; }
            set { _numerodemercosul = value; }
        }

        public string numeroREFinal
        {
            get { return _numerorefinal; }
            set { _numerorefinal = value; }
        }

        public string numeroREInicial
        {
            get { return _numeroreinicial; }
            set { _numeroreinicial = value; }
        }

        public string ToXML()
        {
            XmlSerializer serializer = new XmlSerializer(typeof(informacaoMercosul));
            MemoryStream ms = new System.IO.MemoryStream();
            serializer.Serialize(ms, this);
            StreamReader sr = new System.IO.StreamReader(ms);
            return sr.ReadToEnd();
        }
    }
}