//////////////////////////
//Generated by XSD2Class.
//////////////////////////
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.IO;

namespace MS2000.Desktop.Classes.SiscomexTransmissao
{
    public partial class listaDeclaracoesTransmissao
    {

        private declaracaoImportacaoTransmissao _declaracao;

        public listaDeclaracoesTransmissao()
        {
            _declaracao = new declaracaoImportacaoTransmissao();
        }

        public declaracaoImportacaoTransmissao declaracao
        {
            get { return _declaracao; }
            set { _declaracao = value; }
        }

        public string ToXML()
        {
            XmlSerializer serializer = new XmlSerializer(typeof(listaDeclaracoesTransmissao));
            MemoryStream ms = new System.IO.MemoryStream();
            serializer.Serialize(ms, this);
            StreamReader sr = new System.IO.StreamReader(ms);
            return sr.ReadToEnd();
        }
    }
}