//////////////////////////
//Generated by XSD2Class.
//////////////////////////
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.IO;

namespace MS2000.Desktop.Classes.SiscomexTransmissao
{
    public partial class pagamentoTributos
    {

        private string _codigobancopagamentotributo;
        private string _codigoreceitapagamento;
        private string _datapagamentotributo;
        private string _numeroagenciapagamentotributo;
        private string _valorjurospagamentotributo;
        private string _valormultapagamentotributo;
        private string _valortributopago;

        public string codigoBancoPagamentoTributo
        {
            get { return _codigobancopagamentotributo; }
            set { _codigobancopagamentotributo = value; }
        }

        public string codigoReceitaPagamento
        {
            get { return _codigoreceitapagamento; }
            set { _codigoreceitapagamento = value; }
        }

        public string dataPagamentoTributo
        {
            get { return _datapagamentotributo; }
            set { _datapagamentotributo = value; }
        }

        public string numeroAgenciaPagamentoTributo
        {
            get { return _numeroagenciapagamentotributo; }
            set { _numeroagenciapagamentotributo = value; }
        }

        public string valorJurosPagamentoTributo
        {
            get { return _valorjurospagamentotributo; }
            set { _valorjurospagamentotributo = value; }
        }

        public string valorMultaPagamentoTributo
        {
            get { return _valormultapagamentotributo; }
            set { _valormultapagamentotributo = value; }
        }

        public string valorTributoPago
        {
            get { return _valortributopago; }
            set { _valortributopago = value; }
        }

        public string ToXML()
        {
            XmlSerializer serializer = new XmlSerializer(typeof(pagamentoTributos));
            MemoryStream ms = new System.IO.MemoryStream();
            serializer.Serialize(ms, this);
            StreamReader sr = new System.IO.StreamReader(ms);
            return sr.ReadToEnd();
        }
    }
}