// <auto-generated />
namespace Avaliacao.Gerenciador.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _01Categoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01Categoria));
        
        string IMigrationMetadata.Id
        {
            get { return "201310161756537_01Categoria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
