//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MSIndicadores.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Frequencia_Acidente> Frequencia_Acidente
        {
            get
            {
                if ((_Frequencia_Acidente == null))
                {
                    _Frequencia_Acidente = base.CreateObjectSet<Frequencia_Acidente>("Frequencia_Acidente");
                }
                return _Frequencia_Acidente;
            }
        }
        private ObjectSet<Frequencia_Acidente> _Frequencia_Acidente;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Frequencia_Acidente EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFrequencia_Acidente(Frequencia_Acidente frequencia_Acidente)
        {
            base.AddObject("Frequencia_Acidente", frequencia_Acidente);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MS2000Model", Name="Frequencia_Acidente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Frequencia_Acidente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Frequencia_Acidente object.
        /// </summary>
        /// <param name="pK_ID">Initial value of the PK_ID property.</param>
        /// <param name="ano">Initial value of the Ano property.</param>
        /// <param name="mes">Initial value of the Mes property.</param>
        /// <param name="total_Horas">Initial value of the Total_Horas property.</param>
        /// <param name="total_Acidentes">Initial value of the Total_Acidentes property.</param>
        public static Frequencia_Acidente CreateFrequencia_Acidente(global::System.Int32 pK_ID, global::System.Int32 ano, global::System.Int32 mes, global::System.Double total_Horas, global::System.Int32 total_Acidentes)
        {
            Frequencia_Acidente frequencia_Acidente = new Frequencia_Acidente();
            frequencia_Acidente.PK_ID = pK_ID;
            frequencia_Acidente.Ano = ano;
            frequencia_Acidente.Mes = mes;
            frequencia_Acidente.Total_Horas = total_Horas;
            frequencia_Acidente.Total_Acidentes = total_Acidentes;
            return frequencia_Acidente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PK_ID
        {
            get
            {
                return _PK_ID;
            }
            set
            {
                if (_PK_ID != value)
                {
                    OnPK_IDChanging(value);
                    ReportPropertyChanging("PK_ID");
                    _PK_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PK_ID");
                    OnPK_IDChanged();
                }
            }
        }
        private global::System.Int32 _PK_ID;
        partial void OnPK_IDChanging(global::System.Int32 value);
        partial void OnPK_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ano
        {
            get
            {
                return _Ano;
            }
            set
            {
                OnAnoChanging(value);
                ReportPropertyChanging("Ano");
                _Ano = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ano");
                OnAnoChanged();
            }
        }
        private global::System.Int32 _Ano;
        partial void OnAnoChanging(global::System.Int32 value);
        partial void OnAnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Mes
        {
            get
            {
                return _Mes;
            }
            set
            {
                OnMesChanging(value);
                ReportPropertyChanging("Mes");
                _Mes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Mes");
                OnMesChanged();
            }
        }
        private global::System.Int32 _Mes;
        partial void OnMesChanging(global::System.Int32 value);
        partial void OnMesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Total_Horas
        {
            get
            {
                return _Total_Horas;
            }
            set
            {
                OnTotal_HorasChanging(value);
                ReportPropertyChanging("Total_Horas");
                _Total_Horas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total_Horas");
                OnTotal_HorasChanged();
            }
        }
        private global::System.Double _Total_Horas;
        partial void OnTotal_HorasChanging(global::System.Double value);
        partial void OnTotal_HorasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Total_Acidentes
        {
            get
            {
                return _Total_Acidentes;
            }
            set
            {
                OnTotal_AcidentesChanging(value);
                ReportPropertyChanging("Total_Acidentes");
                _Total_Acidentes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total_Acidentes");
                OnTotal_AcidentesChanged();
            }
        }
        private global::System.Int32 _Total_Acidentes;
        partial void OnTotal_AcidentesChanging(global::System.Int32 value);
        partial void OnTotal_AcidentesChanged();

        #endregion
    
    }

    #endregion
    
}
